language: python
build_environment: ubuntu1304
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install swig
install: pip install --use-mirrors -r requirements.txt
script: python tests/test.py unit
